### PR TITLE
Prefer one expectation per `it`

### PR DESCRIPTION
**Pull request by acostanzo**
This PR came from a conversation started here: https://github.com/BuoySoftware/Wharf/pull/3865#discussion_r1682948116

### CODE REVIEW

**Review by tute — APPROVED** [review]
I had a similar thought Joshua, but my mind was more on integration types of tests, where an object collaborates with many others. We don't have such a rule for feature specs, maybe integration tests like that could also be the exception to this rule (I can find an example in `spec/lib/` if it helps). I like the rule.

**Review by cchatham — APPROVED** [review]
While Josh and Tute make excellent points, I agree with this sentiment even for feature specs. Tests should only test one thing at a time so that it easier to figure out what is wrong when they fail. I would hope we would soon remove many of our feature specs as the automation suite grows in maturity which would remove the slowness from our PR builds.

**Comment by joshuaswilcox** [comment]
I dont see how it would sensible to test only one thing in a feature tests.  We use a pattern of:

Go to a page
Expect page to have content
Do an action
Expect page to not have content

as an example, to breaking that into multiple test would not make it very useful.

**Comment by chadellison** [comment]
Moving this over here from https://github.com/BuoySoftware/Wharf/pull/3865#discussion_r1683034296
I think it makes sense to have one expectation per unit test and multiple expectations for integration / acceptance tests, with the idea that the unit tests should stub expensive state setup, like db transactions (though I know this is not always possible). I think the benefit to having one expectation is being able to see what failed more quickly. I can imagine exceptions to this as well / times where it may make sense to have multiple. I'm curious about others' thoughts though.

**Pull request merged**
