### PR TITLE
Use methods in ViewComponent templates

### PR DESCRIPTION
**Pull request by dgalarza**

### CODE REVIEW

**Review by tute — APPROVED** [review]
Yep! Should we keep the "why"? Your link to the [Avdi Grimm episode](https://graceful.dev/courses/the-freebies/modules/ruby-language/topic/episode-004-barewords/#:~:text=A%20bareword%20in%20Ruby%20might,the%20value%20is%20defined%20in) can be so helpful to sink in the idea.

**Comment by dgalarza** [comment]
@tute what do you think of me adding a new entry into the `Ruby` guides:

> Prefer bare words to instance variables
and linking to that episode there?

**Review by tysongach — APPROVED** [review]

**Comment by tute** [comment]
Makes sense to me Damian. Thank you!

**Comment by nmertaugh** [comment]
> @tute what do you think of me adding a new entry into the `Ruby` guides:
> 
> > Prefer bare words to instance variables
> 
> and linking to that episode there?

Great episode, I'd be glad to see a bare words nudge in our guides.  :1st_place_medal:

**Review by nmertaugh — APPROVED** [review]
+1 for linking Avdi's bare words video

**Review by acostanzo — APPROVED** [review]

**Pull request merged**
